repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/pylint
    rev: v2.14.0-b1
    hooks:
    - id: pylint
      additional_dependencies: ['pylint-airflow','apache-airflow[aws,kubernetes,redis,ssh,sftp,celery]']
      name: pylint dags
      files: dags/
      exclude: ^dags/automated_reporting/

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
