# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 10s

scrape_configs:
- job_name: statsd-exporter
  metrics_path: '/metrics'
  static_configs:
  - targets: ['statsd-exporter:9102']
    labels:
      exporter: 'statsd'
- job_name: airflow-exporter
  metrics_path: '/admin/metrics'
  static_configs:
  - targets: ['airflow-web:8080']
    labels:
      exporter: 'airflow'
