---
name: Airflow Dags Action

on:
  push:
    paths:
      - 'dags/**'
      - 'scripts/**'
      - 'tests/**'
      - 'plugins/**'
      - 'var.json'
      - '.github/workflows/**'
      - 'requirements-dev.txt'
      - 'requirements.txt'
      - 'constraints.txt'
  pull_request:
    types: [opened, reopened]
    branches:
      - master
      - develop
    paths:
      - 'dags/**'
      - 'scripts/**'
      - 'tests/**'
      - 'plugins/**'
      - 'var.json'
      - '.github/workflows/**'
      - 'requirements-dev.txt'
      - 'requirements.txt'
      - 'constraints.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Airflow Dags Action
    steps:
      - name: checkout git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Validate DAGs'
        uses: jayamanikharyono/airflow-dag-action@v2.3
        with:
          requirementsFile: requirements.txt
          dagPaths: dags
          varFile: var.json
          loadExample: False
          connFile: conns.json
          pluginPaths: plugins
          accessToken: ${{ secrets.GITHUB_TOKEN }}