  ---
name:  Flake8 Lint

on:
  push:
    paths:
      - 'dags/**'
      - 'scripts/**'
      - 'tests/**'
      - 'plugins/**'
      - '.github/workflows/**'
  pull_request:
    types: [opened, reopened]
    branches:
      - master
      - develop
    paths:
      - 'dags/**'
      - 'scripts/**'
      - 'tests/**'
      - 'plugins/**'
      - '.github/workflows/**'

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python -m pip install flake8
      - name: flake8 cleanup imported but unused
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: |
            flake8 . --exclude Dockerfile --ignore=E501,W503,W605,F811,F841,E722,E711,E131,E203
