name: CI
on:
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        airflow-version: [2.2.2]
    name: job1
    steps:
      - name: start minikube
        id: minikube
        with:
          minikube-version: 1.24.0
          driver: docker
          container-runtime: containerd
          kubernetes-version: v1.21.3
          cni: bridge
        uses: medyagh/setup-minikube@master
      # now you can run kubectl to see the pods in the cluster
      - name: kubectl
        run: kubectl get pods -A
      - name: checkout git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: run test k8s
        run: |
          pip install kubetest
          pytest  --kube-config=./.kube/config test_nginx.py
